Logical: MedicationTreatmentLine
Title: "Medication Treatment Line - logical model"
Description: "A model for representing a Treatment Line."
* medication[x] 1..1 Reference(MedicinalProduct) or CodeableConcept "Medicinal product for which the treatment line refers to. Identification or sufficient description of the product."
* status 1..1 code "Status of the treatment line"
* verificationInformation 0..1 BackboneElement "Last verification of full overview. The overview is verified as a whole, but each lines is equipped with the information"
  * practicioner 1..1 Reference "HCP verifying the treatments/overview"
  * verificationTime 1..1 dateTime ""
* category 0..* code "Whatever category for the treatment line. Categorisation of treatment lines is implementation-specific."
* medicationTreatment 0..* Reference(MedicationTreatment) "Grouper of lines that belong together, lines are parts of the same treatment"
* indication 0..* code "Reason why the product has been prescribed to the patient, or why the patient claims to be taking it"
* indicationText 0..1 string "Textual explanation for why the medication has been prescribed or why the patient is taking it. This might not be allowed by some implementations."
* usageInstructions 0..* Reference(DosagingInformation) "Instructions about requested administration of the product. Unfinished. See FHIR Dosage for now"
* preparationInstructions 0..* string "Additional instructions about preparation or dispense" 
* noSubstitution 0..1 BackboneElement "Substitution is not allowed for a given reason" 
  * noSubstitutionFlag 1..1 boolean "Substitution of the product is not allowed."
  * noSubstitutionReason 0..1 CD "Coded reason for the no-substitution requirement"
  * noSubstitutionReasonText 0..1 ST "Textual reason for the no-substitution requirement"

* reportingMetadata 1..1 BackboneElement "Metadata abour reporting/authoring of the treatment line"
  * reporter 1..1 Reference(PractitionerBasic) "Person authoring/cancelling the treatment line, either by requesting a treatment or documenting a patient's statement. Typically a doctor, nurse, or pharmacist."
  * reportingTime 1..1 dateTime "Time of creation of the treatment line"
  * patientReported 1..1 boolean "The treatment line has been documented according to patient's statement"
  * author 0..1 Reference(PractitionerBasic) "HCP who takes the decision for prescribing the medication. !!Needs a better name, author is too generic."
  * authoringTime 0..1 dateTime "The time the decision was made. Normally, the same time as reporting time when it's the same person."

* relatedRequest 0..* Reference "Prescriptions that have been authored based on the verified treatment line, or which have been the source for creating the unverified treatment line"
* relatedStatement 0..* Reference "Medication-related statements from patients, pharmacists, or other HCPs, that are related to the verified treatment line or are the source for creating the unverified treatment line"

* relatedDispensation 0..* Reference "Related dispensations that are NOT related to existing prescriptions/requests/statements. Allowing this is very implemenation-specific."
* relatedAdministration 0..* Reference "Related administrations that are NOT related to existing prescriptions/requests/statements. This might be relevant for hospital/home nursing use cases."
* informationSource 0..* Reference "Other data object that this treatment line is derived from"
// comment is modelled to the MedicationOverview object with a reference to treatment line. In FHIR resources could be the other way around.
