@startuml
skinparam backgroundcolor transparent
skinparam linetype polyline

title MEOW Actor Diagram

agent "  [[actors_and_transactions.html#13311-medication-overview-consumer Medication Overview Consumer ]]" as MOvC #Application
agent "  [[actors_and_transactions.html#13312-medication-overview-responder Medication Overview Responder ]]" as MOvR #Application

MOvC -- MOvR : "   [[PHARM-11.html PHARM-11 Retrieve Medication Overview]] ↓  *(option)*          \n\n   [[PHARM-12.html PHARM-12 Query Medication Resources]] ↓"

@enduml
