Logical: MedicationOverview
Title: "Medication Overview - logical model"
Description: "A model for the whole medication overview (medication schema)"
* patient 1..1 Reference(Patient) "Patient"
* medicationTreatmentLine 0..* Reference(MedicationTreatmentLine) "List item in the list of all current medication based treatments. Each line can be verified or unverified."
* verification 0..1 BackboneElement "Verification of overview"
  * practicioner 1..1 Reference "HCP verifying the treatments/overview"
  * verificationTime 1..1 dateTime ""
* comment 0..* BackboneElement "Comment on the full overview"
  * author 1..1 Reference "author of the comment (pharmacist, doctor, social carer)"
  * date 1..1 dateTime "time of comment"
  * commentText 1..1 string "content of the comment"
  * subject 0..* Reference "What the comment is about. It can reference either a treatment line, treatment, or full overview"


Logical: MedicationTreatment
Title: "Medication Treatment - logical model"
Description: "Grouping of treatment lines that are somehow related to eachother (the same purpose, other)"

* advice 0..* BackboneElement "Advice"
* comment 0..* BackboneElement "Comment"
* indication 0..* code "Reason why the product has been prescribed to the patient, or why the patient claims to be taking it"
// * medicationTreatmentLine 1..* "Medication treatment line"

Logical: MedicationTreatmentLine
Title: "Medication Treatment Line - logical model"
Description: "A model for representing a Treatment Line."
* medication[x] 1..1 Reference(MedicinalProduct) or CodeableConcept "Medicinal product for which the treatment line refers to. Identification or sufficient description of the product."
* status 1..1 code "Status of the treatment line"
* verificationInformation 0..1 BackboneElement "Last verification of full overview. The overview is verified as a whole, but each lines is equipped with the information"
  * practicioner 1..1 Reference "HCP verifying the treatments/overview"
  * verificationTime 1..1 dateTime ""
* category 0..* code "Whatever category for the treatment line. Categorisation of treatment lines is implementation-specific."
* medicationTreatment 0..* Reference(MedicationTreatment) "Grouper of lines that belong together, lines are parts of the same treatment"
* indication 0..* code "Reason why the product has been prescribed to the patient, or why the patient claims to be taking it"
* indicationText 0..1 string "Textual explanation for why the medication has been prescribed or why the patient is taking it. This might not be allowed by some implementations."
* usageInstructions 0..* BackboneElement "Instructions about requested administration of the product. Unfinished. See FHIR Dosage for now"
  * timing 0..1 BackboneElement "Time-related attributes related to administration"
    * startMedicationDate 1..1 dateTime "Start date of the medication" "Start date of the medication"
    * endMedicationDate 0..1 dateTime "End date, if exists, for stopping the medication" "End date, if exists, for stopping the medication"
    * duration 0..1 Quantity "Duration of the treatment"
  * dosage 0..1 BackboneElement "strength, amount. Can be complex model, one dosage for odd days, another for even days"
    * dose 0..1 Quantity "A dose to be administered at one time"
    * frequency 0..1 Ratio "Administered amount per time unit"
  * routeOfAdministration 0..1 code "Route of administration for this particular treatment"
* preparationInstructions 0..* string "Additional instructions about preparation or dispense" 

* reportingMetadata 1..1 BackboneElement "Metadata abour reporting/authoring of the treatment line"
  * reporter 1..1 Reference "Person authoring/cancelling the treatment line, either by requesting a treatment or documenting a patient's statement. Typically a doctor, nurse, or pharmacist."
  * reportingTime 1..1 dateTime "Time of creation of the treatment line"
  * patientReported 1..1 boolean "The treatment line has been documented according to patient's statement"
  * author 0..1 Reference "HCP who takes the decision for prescribing the medication. !!Needs a better name, author is too generic."
  * authoringTime 0..1 dateTime "The time the decision was made. Normally, the same time as reporting time when it's the same person."

* relatedRequest 0..* Reference "Prescriptions that have been authored based on the verified treatment line, or which have been the source for creating the unverified treatment line"
* relatedStatement 0..* Reference "Medication-related statements from patients, pharmacists, or other HCPs, that are related to the verified treatment line or are the source for creating the unverified treatment line"

* relatedDispensation 0..* Reference "Related dispensations that are NOT related to existing prescriptions/requests/statements. Allowing this is very implemenation-specific."
* informationSource 0..* Reference "Other data object that this treatment line is derived from"
// comment is modelled to the MedicationOverview object with a reference to treatment line. In FHIR resources could be the other way around.

Logical: MedicinalProduct
Title: "Medication for clinical workflows"
Description: "Medication information. The model is shared by statements, requests, dispensations, and treatment lines. Each of those may have different restrictions in FHIR profile."

* medicinalProductIdentifier 0..* II "MPID or national identifier"
* packagedProductIdentifier 0..* II "PCID or national"
* pharmaceuticalProductIdentifier 0..* II "PhPID or national virtual/administrable product code"
* atc 0..1 CD "ATC code"
* classification 0..* CD "Classification (narcotic/psychotropic; orphan drug; etc)"
* packSize 0..* PQ "Overall amount of product in one virtual or real package (100ml; 20 tablets; 1 creme & 6 pessaries)"
* productName 0..* Class "Name of the product (full name, invented name, other)"
  * name 1..1 ST "Name of type and language that is relevant for the users"
  * language 0..1 CD "Language of the name"
  * type 0..1 CD "Type of the name (full name, common name, etc)"
* doseForm 0..* Class "Dose form(s) on a product level. Dose form for a single package item is defined below."
  * formCode 1..1 CD "Coded dose form"
  * type 0..1 CD "The type of dose form (combined, authorised, administrable...)" 

* item 0..* Class "A medication item. For combination packs, this can be manufactured items with each item having its own dose form and ingredients+strengths defined"
  * doseForm 0..1 Class "Dose form of single item"
    * formCode 1..1 CD "Dose form"
    * type 0..1 CD "The type of dose form (typically manufactured dose form)" 
  * ingredient 1..* Class "Ingredients"
    * role 0..1 CD "Role (active ingredient, excipient). Typically excipients are not needed, so by default active ingredients are expected."
    * substance 1..1 CD "Substance"
    * strengthInfo 1..* Class "Concentration or presentation strength"
      * strength 1..1 RTO "Concentration or presentation strength of the precise active ingredient"
      * strengthType 1..1 CD "Type of strength that is expressed"
      * strengthSubstance 0..1 CD "Substance that the strength refers to, if different from the main substance"
  * unitOfPresentation 0..* CD "Unit of presentation for the manufactured item (tablet, vial, tube). Typically, the smallest countable object in the package."
  * containedQuantity 0..1 PQ "Manufactured item quantity for liquids (3ml/vial)"
  * manufacturedItemQuantity 0..1 PQ "Number of such manufactured items in this product (5 vials)"
* device 0..* Class "Administrative device included in the product"
  * deviceQuantity 1..1 PQ "Number of such devices"
  * device 1..1 CD "Device coded"
* marketingAuthorisationHolder 0..1 ST "MAH name - do we need more?"
* routeOfAdministration 0..* CD "Route of Administration - if we need it on product level"
// Shall we have some text?

Logical: DosagingInformation
Title: "Dosaging"
Description: "Usage instructions. Instructions about requested administration of the product. Based on FHIR Dosage complex data type."

* sequence 0..1 INT "Order of the dosage instruction, in case one treatment consists of several dosaging schemes"
* text 0..1 ST "Free text usage/dosage instructions"
* additionalInstruction 0..* CD "Coded instructions, e.g warnings to the patient, like 'may cause drowsiness' etc"
* patientInstruction 0..1 ST "Patient oriented instructions as free text"
* timing 0..1 Class "When medication should be administered (period, time of day, frequency, etc)" 
  * event 0..* dateTime "Exact date and/or time of the administration"
  * code 0..1 CD "Timing abbreviation (AM - morning, Q4H - once in every 4 hours, BID - twice a day, etc)"
  * repeat 0..1 Class "Repetition of the administration."
    * bounds 0..1 Class "Time bounds for the treatment (current dosaging scheme). Only one of the following can exist."
      * duration 0..1 PQ "Number of time units, e.g 10 days"
      * range 0..1 Range "A range of numbers of time units, 5-10 days"
      * period 0..1 Period "Start and end date, 05.08.2023 - 10.08.2023"
    * count 0..1 Class "Number of times to repeat, exact or range"
      * count 1..1 INT "Number of times (e.g 'once', '10 times')"
      * countMax 0..1 INT "Maximum number of times (e.g 'maximum 10 times')"
    * duration 0..1 Class "Duration of one administration, exact or range"
      * duration 1..1 PQ "Duration of administration (e.g '5 minutes', '1 hour')"
      * durationMax 0..1 PQ "Maximum duration of administration (e.g 'maximum 1 hour')"
    * frequency 0..1 Class "Frequency of intake/administration (e.g 'three times a day')"
      * numberOfTimes 1..1 INT "Number of times per period (e.g '3 times')"
      * maxNumberOfTimes 0..1 INT "Maximum number of times per period (e.g. 'maximum 3 times')"
      * period 1..1 PQ "Duration to which the frequency applies (e.g '... / 1 day')"
      * periodMax 0..1 PQ "Upper limit of the period (e.g ... / 3-4 days)"
    * dayOfWeek 0..* CD "The day of the week of administration, e.g Mon, Tue, etc"
    * timeOfDay 0..* time "Time of day of administration (e.g '10:00')"
    * eventTime 0..* Class "An event the administration is bound to, e.g 'before meal', '30 min before meal'"
      * when 0..* CD "Time period or event ('before meal', 'immediately', 'morning')"
      * offset 0..1 INT "minutes from event, before or after (?not sure how to show before/after with only positive integers)"
* asNeeded 0..1 BL "Take as needed"
* asNeededFor 0..* CD "Take as needed for the coded reason"
* bodySite 0..1 CD "Body site of administration"
* routeOfAdministration 0..1 CD "Route of administration"
* methodOfAdministration 0..1 CD "Method of administration"
* doseAndRate 0..* Class "Amount of medication administered per one dose (= one timing)"
  * type 0..1 CD "The kind of dose or rate specified (e.g calculated, ordered, etc)"
  * dose 0..1 PQ "!Range or SimpleQuantity. Amount of medication per one dose."
  * rate 0..1 RTO "!Ratio, Range or SimpleQuantity. Amount of medication per unit of time. ?See examples to see how dose+rate work together."
* maxDose 0..* Class "Maximum dose for the patient"
  * maxDosePerPeriod 0..* RTO "Upper limit on medication per unit of time"
  * maxDosePerAdministration 0..1 PQ "Upper limit on medication per one administration"
  * maxDosePerLifetime 0..1 PQ "Upper limit on medication per lifetime of the patient"